name: CLA Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for CLA Signature
        uses: cla-assistant/github-action@v2.2.1
        with:
          path-to-signatures: 'CLA/signatures.json'
          path-to-clafile: 'CLA/individual_cla.md'
          allowlist: |
            apercu-labs-bot
            signorabraham
          branch: main
